# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb5a8e32e5895b310d7bdcb1a193fb36062cfe5786d6a16b0de09d65caa7d4f2bc545fb9c1944872d5126438ad1afe9c7951adafa981f34563ef2ec3599017f

test:
  secret_key_base: f4b0b19495a1c2bf98a144ca02f02344af76aff41899baec49aec22ecb5ab2be18c2fe63c090abf8dd49242c3895edbb90fdb916e2ea8a6485ea8207f4bf14f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
